# Generated by Django 4.0.1 on 2023-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Photo', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
