# Generated by Django 4.0.1 on 2023-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
