# Generated by Django 4.0.1 on 2023-01-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0002_alter_airline_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='Id',
            new_name='Airline_Id',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Photo',
            new_name='Airline_Photo',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Name',
            new_name='Airline_name',
        ),
    ]
