# Generated by Django 4.1.7 on 2023-03-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0003_rename_id_airline_airline_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_manager',
            fields=[
                ('Airline_username', models.IntegerField(primary_key=True, serialize=False)),
                ('Airlien_password', models.CharField(max_length=10)),
                ('Airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.airline')),
            ],
        ),
    ]
