# Generated by Django 4.1.7 on 2023-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0004_airline_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_manager',
            name='Airline_username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
