# Generated by Django 4.0.1 on 2023-01-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0002_alter_flight_flights_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='Departing_time',
        ),
    ]
