# Generated by Django 4.0.1 on 2023-01-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0003_remove_flight_departing_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arriving_time',
            new_name='Arriving_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Flights_id',
            new_name='Flight_id',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='total_ticket',
            new_name='Total_ticket',
        ),
    ]
