# Generated by Django 4.0.1 on 2023-01-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0004_rename_arriving_time_flight_arriving_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='Arriving_time',
            new_name='Depart_time',
        ),
    ]
