# Generated by Django 4.0.1 on 2023-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0005_rename_arriving_time_flight_depart_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airline_logo', models.ImageField(upload_to='media/')),
                ('Airline_name', models.CharField(max_length=100)),
                ('Flightname1', models.CharField(max_length=100)),
                ('Flightname2', models.CharField(max_length=100)),
                ('Timeduration', models.CharField(max_length=100)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
    ]
