# Generated by Django 4.0.1 on 2023-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0006_flight_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_component',
            name='Arrive_time',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='flight_component',
            name='Depart_time',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='flight_component',
            name='component_Id',
            field=models.IntegerField(default=0),
        ),
    ]
