# Generated by Django 4.0.1 on 2023-01-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0007_flight_component_arrive_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_component',
            old_name='component_Id',
            new_name='Flight_Id',
        ),
    ]
