# Generated by Django 4.0.1 on 2023-01-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0008_rename_component_id_flight_component_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_component',
            name='Total_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
