# Generated by Django 4.0.1 on 2023-01-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0010_remove_flight_component_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_component',
            name='Temparal_ID',
            field=models.IntegerField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
    ]
