# Generated by Django 4.0.1 on 2023-01-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0011_alter_flight_component_temparal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_component',
            name='Airline_name',
            field=models.CharField(default='airline', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight_component',
            name='Flight_Id',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='flight_component',
            name='Temparal_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
