# Generated by Django 4.0.1 on 2023-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0015_alter_flight_component_temparal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_component',
            name='Temparal_ID',
            field=models.IntegerField(default=138936737986651167, primary_key=True, serialize=False),
        ),
    ]
