# Generated by Django 4.0.1 on 2023-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0016_alter_flight_component_temparal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_component',
            name='Temparal_ID',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
