# Generated by Django 4.1.7 on 2023-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0017_alter_flight_component_temparal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_component',
            name='Sr_no',
            field=models.IntegerField(default=0),
        ),
    ]
