# Generated by Django 4.1.7 on 2023-03-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='User_profile',
            new_name='Profile',
        ),
    ]
