# Generated by Django 4.1.7 on 2023-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_profile_user_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
    ]
