# Generated by Django 4.1.7 on 2023-03-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='Balance',
        ),
    ]
