# Generated by Django 4.1.7 on 2023-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
    ]
