# Generated by Django 4.1.7 on 2023-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='Balance',
            field=models.IntegerField(default=500),
        ),
    ]
